### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/raw_data/ml-latest-small/keywords_in_id.pkl'

### ISSUE THREAD

**Issue by luoluo1997a** [Suikasxt/PMG#1]
您好，感谢开源代码。请问keywords_in_id.pkl这个文件是如何生成的呢？

**Comment by Suikasxt** [comment]
keywords_in_id.pkl中存储的是预处理好的item keywords，其调用函数在PMGInference的generateItemKeywords方法中，完整的pkl生成脚本已经添加到根目录下的generate_item_keywords.py。
